services:
  ook-lang:
    build: .
    container_name: ook-runner
    stdin_open: true
    tty: true
    volumes:
      - ./hello.ook:/app/hello.ook
      - ./output.ook:/app/output.ook
      - ./ook.py:/app/ook.py
      - ./text_to_ook.py:/app/text_to_ook.py
